#ROUTES
openapi: 3.1.0
info:
  title: 'Ecommerce JaggerStore'
  version: '1.0.0'
  description: 'Documentacion para administrar los productos en API'
  contact:
    name: 'Nicolas Andreolli'
servers:
  - url: 'http://localhost:8080' 
paths:
  /api/carts:
    get:
      summary: Obtains the user's cart.
      tags:
        - Carts:
      responses:
        "200":
          description: The cart was successfully obtained.
        "400":
          description: Cart not found.
        "500":
          description: An internal server error occurred.
  /api/carts/purchase?:
    get:
      summary: Make the purchase and obtain the purchase ticket.
      tags:
        - Purchase:
      responses:
        "200":
          description: Purchase made, ticket obtained.
        "400":
          description: Error during the process.
        "500":
          description: An internal server error occurred.

  /api/carts/add-to-cart:
    post:
      summary: Add a product to the user's cart.
      tags:
        - AddToCart:
      responses:
        "200":
          description: Product successfully added to cart.
        "400":
          description: Error when adding product to cart.
        "500":
          description: An internal server error occurred.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"

  /api/carts/remove-from-cart:
    post:
      summary: Remove product from cart.
      tags:
        - RemoveFromCart
      responses:
        "200":
          description: Product has been successfully removed from your cart.
        "400":
          description: Error when removing product from cart.
        "500":
          description: An internal server error occurred.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Cart"
                - $ref: "#/components/schemas/Product"

  /api/carts/update-quantity:
    post:
      summary: Update the number of product units added to cart.
      tags:
        - UpdateQty
      responses:
        "200":
          description: Quantity successfully updated.
        "400":
          description: Error when updating the product quantity.
        "500":
          description: An internal server error occurred.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#components/schemas/Cart"
                - $ref: "#components/schemas/Product"

# COMPONENTS
components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID auto-generated by MongoDB.
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID of the product.
              quantity:
                type: number
                default: 0
      required:
        - products

    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID auto-generated by MongoDB
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        price:
          type: number
          required: true
        status:
          type: boolean
          required: true
        code:
          type: string
          required: true
        stock:
          type: number
          required: true
        category:
          type: string
          required: true
        thumbnail:
          type: array
          items:
            type: string
